### ISSUE TITLE
Продумать сборку

### ISSUE THREAD

**Issue by lirik90** [svetit-io/svetit#1]
Сейчас Dockerfile лежит в src/back и собирает единственный МС src/back/auth. В докерфайле сначала устанавливаются зависимости, а затем собирается МС который в свою очередь сам собирает UServer. Когда МС станет больше, получится что при сборке каждого МС, отдельно собирается userver. Нужно изучить наличие возможности отдельно собирать userver, а затем собирать только код самих МС без повторной пересборки userver.

**Comment by prt0117** [comment]
возможно, поможет вариант, чтобы был образ src отдельный (служебный, не отдельный мс), в котором бы происходила сборка. Этот образ собирался бы первым. И в момент сборки последующих образов через [COPY --from=](https://docs.docker.com/engine/reference/builder/) копировался уже готовый userver из src образа.
