### ISSUE TITLE
Валидация данных по json схемам

### ISSUE THREAD

**Issue by lirik90** [svetit-io/svetit#100]
Схема работы:
1. В папке doc/api/ подготавливаем openapi документацию.
2. При сборке запускаем `swagger2jsonschema doc/api/api.yaml` создания json схем и наших кастомных схем для ручек.
3. При сборке контейнера копируем схемы в контейнер при обычной сборке куда то рядом с исполняемым файлом
4. Заводим конфиг для указания пути к схемам
5. При создания обработчика ручки достаём из конфига путь к схемам и возможно на основании имени ручки или просто новым параметром в каждой ручки который указывал бы имя файла для ручки, загружаем кастомную схему с описанием входных параметров ручки. В этом кастомном файле должны быть ссылки на json схемы для ручки.
6. Загрузив json'ы при создании обработчика ручки мы должны засунуть их в мапу с методами map<MethodName, StructWithRequestSchemaAndJsonSchema>
7. При вызове ручки мы должны достать из мапы наши схемы auto& schemas = _shemas[req.Method()]
8. и проверить сначала с помощью нашей кастомной (RequestSchema) входные параметры запроса,  `ValidateRequest(req, schemas.request)`
9. а затем проверить тело запроса, если оно есть, с помощью json схемы  `formats::json::Validate(jsonBody, schemas.json)`
10. В реализации кстомного `ValidateRequest` нужно проверять query параметры и headers, т.е. всё что описано в разделе properties в openapi описании у ручки.
11. Реализовать создание кастомных схем с описанием параметров запроса нужно в нашем форке openapi2jsonschema https://github.com/lirik90/swagger2jsonschema

```cpp
struct RequestAndJsonSchema {
  formats::json::Schema json;
  RequestSchema request;
};
```

Для валидации json по json схеме есть пример тут: userver/universal/src/formats/json/validate_test.cpp

План работ:
1. Описать один метод (с json в теле) одной ручки в doc/api/api.yaml но вынести тело запроса в отдельный файл например doc/api/Project.yaml и подключить его в файл doc/api/api.yaml используя $ref по документации openapi
2. Проверить сработает ли swagger2jsonschema с таким выносом
3. Описать несколько (2-3) ручек в доке (если сработал предыдущий пункт, то с выносом в разные файлы, если нет, то всё в одном файле.
4. доработать openapi2jsonschema в нашем форке так чтобы он генерировал json из раздела properties описания ручек, но json так же должен включать в себя ссылку на body схему и operationId. В качестве имени генерируемого файла, предлагаю использовать operationId который надеюсь получится привязать к имени ручки для того чтобы не заводить доп.параметр при загрузки файла схемы при создании обработчика ручки.
5. добавить параметр в конфиг одного из МС который будет содержать путь до папки со схемами
6. использовать параметр для загрузки схем в описанных в доке ручках.
7. встроить запуск swagger2jsonschema в процесс сборки
8. написать шаблон для простых ручек который будет принимать имя ручки и тип тела

**Comment by prt0117** [comment]
Примечания после реализации прототипа:

1) format: uuid не учитывается валидатором при проверке по схеме с query параметрами и заголовками. Поэтому если передать вместо uuid, например, строку "123" (допустим, в заголовке X-User), то валидируется успешно. Нужно подумать, как либо донастроить валидатор (может, другой драфт для jsonSchema нужен?), либо реализовать дополнительную проверку ручную для этого случая.

2) сейчас у нас в тестовом api.yaml запросы POST и PATCH одной ручки используют ref на одинаковое тело. В этом теле параметр id указан не обязательным, что корректно для POST, но не корректно для PATCH (хотя, конечно, если id не передать, то упадёт, но, возможно, с 500 статусом уже). Поэтому вопрос - по простому будет использовать ref на другое тело в api.yaml. Либо, может быть, возможен какой-то полиморфизм в yaml файле, чтобы использовать то же тело, но указать ещё один обязательный параметр.

3) пункт из плана "написать шаблон для простых ручек который будет принимать имя ручки и тип тела" до конца не понял. Требуется уточнение.

4) и ещё момент - поскольку мы сейчас уже научились валидировать в том числе и хедеры по схеме, то возникает вопрос, как мы будем выбрасывать 401 ошибку, если именно не хватает заголовка авторизации? Мы ведь сейчас при валидации выбрасываем всегда 400, если валидация не прошла.
