### ISSUE TITLE
Автоматическое создание пользователя в SSO при старте Клока

### ISSUE THREAD

**Issue by lirik90** [svetit-io/svetit#11]

**Comment by prt0117** [comment]
Вариант решения. 

Сначала нужно экспортировать реалм вместе с пользователями ([референс](https://www.keycloak.org/server/importExport)). 

Для этого примонтируем новый volume в docker-compose.yml:
volumes:
      - ./keycloak/import:/opt/keycloak/data/import
      - ./keycloak/export:/tmp/export

Далее перезапустим sso через docker compose down/up -d и выполним команду: 
`docker exec -it svetit_sso /opt/keycloak/bin/kc.sh export --dir /tmp/export --users realm_file --users-per-file 100`

Далее возьмем выгруженный realm и убедимся, что в нём есть пользователи (ctrl+f по слову "users" с кавычками) - сейчас там только пользователь user с паролем 123456

Далее скопируем данный файл в папку /pipeline/keycloak/import и заменим тот файл, который там сейчас, переименовав. И при чистом запуске sso (предварительно удалив volume от Postgres) получим импорт упомянутого выше пользователя user. 

Можно посоздавать несколько нужных юзеров и экспортировать их.

**Comment by lirik90** [comment]
Тестовые пользователи понадобятся для разработки. А при разворачивании на прод нужно сделать так чтобы их не было. В идеале конечно чтобы можно было не только при разворачивании добавлять пользователей, но и тогда когда стенд уже развёрнут чтобы можно было их консоли добавить пользователя. Вроде видел что есть какой то admin-cli у keycloak, может в эту сторону копнём.

Либо можно сделать так как ты предлагаешь, но сделать несколько отдельных конфигов. И команды 
```bash
make up-dev
```
и отдельно для прода
```bash
make up-prod
```

Нужно ещё подумать.
