### ISSUE TITLE
Следить за ключом генерации сессионного токена

### ISSUE THREAD

**Issue by lirik90** [svetit-io/svetit#13]
Нужно следить за изменением файла и при изменении загружать новый ключ.

**Comment by prt0117** [comment]
Нашёл в userver вот такую штуку:
https://userver.tech/db/dca/classengine_1_1io_1_1sys__linux_1_1Inotify.html
https://userver.tech/dc/df1/inotify_8hpp_source.html

Будем её использовать?

Только тут, видимо, надо будет как-то корутину запускать. Это мы ещё не делали целенаправленно.

**Comment by prt0117** [comment]
Реализовал, ПР создал.
