### ISSUE TITLE
Падает валидация

### ISSUE THREAD

**Issue by prt0117** [svetit-io/svetit#162]
Ошибка вот такая в случае, если в доке описан, допустим, 1 параметр (пусть X-User заголовок) и у него required=false, и мы его не передаём при запросе:
```
Wrong params/headers: ValuePath: '#' SchemaPath: '#' Detail: '{"expected":["object"],"actual":"null"}' (svetit::errors::BadRequest400)
```
То есть по логике вещей, если 1 параметр описан, но не обязательный, то валидатор не должен никак ругаться, если мы его не передаём.

**Comment by lirik90** [comment]
А что это за ручки у которых описаны только необязательные параметры? X-User - везде где описан должен быть обязательным кажется, а он ведь есть почти везде кроме ручек авторизации.
В любом случае нужно будет попытаться сделать так чтобы в валидатор передавался пустой json объект а не null когда пользователь ничего не передал.

**Comment by prt0117** [comment]
> А что это за ручки у которых описаны только необязательные параметры? X-User - везде где описан должен быть обязательным кажется, а он ведь есть почти везде кроме ручек авторизации.

например, GET /space?link=. Там получилась такая схема, что даже X-User не обязательный. На случай, когда мы получаем информацию о пространстве по токену ссылки-приглашения, он не нужен. И всё это в одной ручке поскольку описано - разные get параметры, которые влияют на логику работы ручки (?key=, ?id=), - то все параметры не обязательные.

> В любом случае нужно будет попытаться сделать так чтобы в валидатор передавался пустой json объект а не null когда пользователь ничего не передал.

Готовлю фикс.

**Comment by lirik90** [comment]
Во всех ручках параметр x-User обязателен, даже если мы не используем значение. кроме некоторых ручек связанных с авторизацией, но там кажется всегда есть параметры которые обязательные. Есть ещё примеры ручек со всеми необязательными параметрами?
Поправь пожалуйста доку для Get /space

**Comment by prt0117** [comment]
> Есть ещё примеры ручек со всеми необязательными параметрами?

/auth/login
/auth/logout
/auth/logout/callback
