### ISSUE TITLE
переключение локализации по куке

### ISSUE THREAD

**Issue by lirik90** [svetit-io/svetit#165]
Нужно избавится от префикса в пути фронта.
Сейчас в index.html есть что-то вроде <base href="/ru/"> и прокся отдаёт вариант собранного фронта на основе этого префикса пути. Нужно заменить это на куку и анализировать куку на проксе.

**Comment by prt0117** [comment]
Вот это то, что нам нужно?
https://stackoverflow.com/questions/70366657/nginx-configuration-for-angular-with-multi-language-i18n-support

**Comment by prt0117** [comment]
Влил первые доработки (без бэка, только конфиг прокси + настройка на уровне ангулара) для избавления от языка в url. Работает (без переключения языка через выпадашку и пока на основе заголовка Accept-Language).

Но как это всё должно работать?

1) При первом заходе по корню открывается фронт, который редиректит на /auth/login, так? Далее после этапа SSO, происходит редирект на /auth/login_callback, где проставляется авторизационная кука. Значит, мы должны в ручке /auth/login_callback куки с языком проставить? Это будет отдельная кука, судя по всему? Так как авторизационная у нас HttpOnly. И как мы будем определять дефолтный язык? Смотреть на заголовок запроса Accept-Language, который прилетает на /auth/login_callback?

2) Сейчас на проксе анализируется заголовок запроса Accept-Language (+ дефолт идёт русский). Я проверял на файере с настройкой дефолтного значения этого заголовка на en, работает - отображается английская локаль.

3) Далее принудительное переключение языка. Значит, чтобы оно работало, нам как минимум нужна новая ручка, так? В каком мс - в мс авторизации? Данные в эту ручку будут отправляться при клике на языке в выпадашке с языками. Ручка будет записывать полученный язык в куку и присылать 200 ОК с этой кукой. Может ещё нужно в таблицу с сессиями язык записать? А фронт, значит, получив 200 и куку, должен переключить язык (см. следующий пункт).

4) Для переключения языка на фронте нужно будет, наверное, просто обновить страницу средствами JS. И прокся должна будет отдать ту же страницу, на которой был юзер до обновления страницы, но уже с нужным новым языком.

Пока такое понимание. Пожалуйста, поправь, где не прав.

**Comment by lirik90** [comment]
Куку ставим во фронте а не на бэке.

Фронт как только загружается, сразу ставит куку, ещё до проверки авторизации. Nginx проверяет куку и в зависимости от её содержимого устанавливает root для статики.

Когда пользователь нажимает переключить язык, мы меняем значение куки и обновляем страницу.

**Comment by prt0117** [comment]
> Куку ставим во фронте а не на бэке

Тогда, получается, бэк в этой задаче не нужен вообще?

**Comment by prt0117** [comment]
> Куку ставим во фронте а не на бэке.
> 
> Фронт как только загружается, сразу ставит куку, ещё до проверки авторизации. Nginx проверяет куку и в зависимости от её содержимого устанавливает root для статики.
> 
> Когда пользователь нажимает переключить язык, мы меняем значение куки и обновляем страницу.

Всё понял.
