### ISSUE TITLE
Генерация Ангулар HTTP Клиента из свагера

### ISSUE THREAD

**Issue by lirik90** [svetit-io/svetit#166]
Нужна команда в Makefile для генерации. По всей видимости это должен быть запуск какого то докер образа с параметрами.

**Comment by prt0117** [comment]
Образец сгенерированного кода https://github.com/prt0117/openapigenerator-angular-tutorial

**Comment by prt0117** [comment]
Генерация кода происходит командой:

npx openapi-generator-cli generate -i openapi.yaml -g typescript-angular -o client/src/app/core/modules/openapi --additional-properties ngVersion=16.2.14,fileNaming=kebab-case,withInterfaces=true --generate-alias-as-model

Тут нужно обратить внимание на версию Ангулара, указанную в параметре ngVersion. Она должна совпадать с той версией, которую показывает команда ng version.
