### ISSUE TITLE
Разбитие доки на куски

### ISSUE THREAD

**Issue by lirik90** [svetit-io/svetit#167]
Разбитие доки на куски с объединением в один файл на лету перед запуском питон утилиты.
В скрипте который сейчас считает хэш файла и решает нужно ли перегенерировать, нужно в цикле (или find ... -exec ...) посчитать хэш для всех файлов и от получившегося текста посчитать хэш.

**Comment by prt0117** [comment]
получается, можно вот как сделать.
1) сделать dockerfile новый для нового сервиса по аналогии со schemas_generator. FROM от официального образа redocly/cli:latest.
2) скопировать внутрь образа при билде разделенную доку (разделить заранее локально и влить в репу);
3) через RUN в dockerfile запустить генерацию единого api.yaml;
4) далее в schemas_generator при билде образа скопировать этот api.yaml через COPY from= из образа с redocly.
5) ну и дальше всё, как уже сделано.

**Comment by prt0117** [comment]
Ну а для разработки можно доработать generate.sh следующим образом:
1) пусть файлы разделенные хранятся в doc/api/spillted/ ;
2) вычисляем, как ты описывал в задаче, хеш каждого файла рекурсивно, составляем из хешей общий текст и считает хеш от текста. если хэш изменился относительно предыдущего подсчёта, то тогда скрипт выполняется дальше.
3) перед запуском питон утилиты вызовем команду
docker run --rm -v $API_PATH:/spec redocly/cli bundle splitted/api.yaml > api.yml , где API_PATH - это путь до папки svetit/doc/api/
4) после этого запускаем питон утилиту.
