### ISSUE TITLE
узнать для чего нужны имена SQL запросов

### ISSUE THREAD

**Issue by lirik90** [svetit-io/svetit#171]
Нужно ли это только для логирования?
Если это вообще для логирования, то действительно ли это помогает при анализе логов?
Если это что-то бесполезное, то как проще всего от этого избавится?

**Comment by prt0117** [comment]
Ну вот тут пишут, что имя используется для prepared statements https://t.me/userver_ru/16395 Хотя я не уверен, что автор не ошибся тут, потому что где-то в чате поддержки, если мне не изменяет память, встречал инфу, что имя запроса нужно для логирования исключительно. Поищу ещё.

**Comment by prt0117** [comment]
Ну и, ЕМНИП, нужно для метрик.
