### ISSUE TITLE
auth: Добавить синхронизацию потоков

### ISSUE THREAD

**Issue by lirik90** [svetit-io/svetit#18]
- Добавить синхронизацию для GetVerifier
- Проверить другие места и при необходимости добавить синхронизацию

**Comment by prt0117** [comment]
> * Проверить другие места и при необходимости добавить синхронизацию

Посмотрел код мс Авторизации - вроде, таких же критичных мест как там, где добавили мьютекс (см ПР), больше нет. Но точно не уверен.
