### ISSUE TITLE
В api.yaml добиться валидации uuid

### ISSUE THREAD

**Issue by prt0117** [svetit-io/svetit#181]
В параметры, которые должны быть uuid, добавить следующие ограничения:
```
type: string
format: uuid
# помимо уже установленных type и format
minLength: 36
maxLength: 36
pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
```

**Comment by prt0117** [comment]
по 181 задаче появился ещё вопрос.
пусть речь идёт о ручке создания проекта POST /project/project.
мы когда тело будем слать в неё, что мы делаем с id (который никак не используется при создании проекта, так как генерируется):
1) вообще не шлём id, то есть отправляем вот такое тело:
{
	"spaceId": "22222222-2222-2222-2222-222222222222",
	"key": "project2",
	"name": "Project 2",
	"description": "Description of Project 2",
	"changedAt": 1,
	"sync": "projectToNode"
}
2) шлём пустой id = "" или id = null
{
	"id": "",
                ...
}
или
{
	"id": null,
                ...
}

почему это всплыло сейчас. я сейчас добавил ограничения, чтобы валидировался uuid, и теперь тесты падают с id = "" (пустая строка). я начал разбираться - похоже, сериализаторы надо дописывать, сейчас у нас идёт проверка на пустоту id (пустая строка), а надо через HasMember("id") проверять. То есть придётся допилить 1 сериализатор в мс Проекты и 4 шт в мс Пространства. Наверное, в рамках отдельной задачи.

**Comment by lirik90** [comment]
Там можно получить значение и передать значение по умолчанию. Недавно где-то такое делали.

**Comment by prt0117** [comment]
> Там можно получить значение и передать значение по умолчанию. Недавно где-то такое делали.

Ты про вот это? https://github.com/svetit-io/svetit/blob/develop/src/back/project/src/model/param_type_serialize.cpp#L29  
Мы тут именно null слали в теле:
https://github.com/svetit-io/svetit/blob/develop/src/back/project/tests/test_param_type.py#L8

Мне хотелось бы понять, правильно ли заставлять фронт во всех телах слать какой-то параметр, который роли не играет - пустой id, id=null или даже id с каким-то рандомным значением. Или лучше будет, если фронт отправит только те поля, которые у него реально есть и которые, допустим, получены из инпутов формы создания сущности.

Хотя тут ещё нужно учитывать, наверное, момент с генерацией фронта из openapi. Чтобы было как-то проще и удобнее в итоге. Мы же по этому пути собираемся пойти.

**Comment by lirik90** [comment]
Нет. Я про это:
```
json["id"].As<std::string>("");
```
