### ISSUE TITLE
Для ручки POST /space/invitation?link={uuid} неправильно работает валидация

### ISSUE THREAD

**Issue by prt0117** [svetit-io/svetit#195]
Дело в том, что эта ручка ведёт себя по-разному в зависимости от наличия query параметра link. Если он не указан, то берётся тело из запроса и создаётся сущность. А если link указан, то тело не используется, берётся только link и заголовок один и создаётся сущность.

Так вот не понятно, как описать тело, как не обязательное.

Пробовал вот так:
```
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Space.yaml
    required: false
```
не заработало.

Параметры тела все делать не обязательными тоже не получится, так как для случая если link не указан, то эти параметры должны быть обязательными.

Может быть, как-то можно извернуться:
https://stackoverflow.com/questions/35406986/how-to-define-different-body-parameters-for-same-path-in-openapi-swagger

Либо разделить эту ручку на две отдельные.

**Comment by prt0117** [comment]
Поскольку решили ручку разделить на две, нужно понять, как это будем делать.

POST /space/invitation - это будет первая ручка (тот же метод и адрес, как раньше у общей ручки до разделения).

Варианты второй ручки:

1) Можно использовать HEAD /space/invitation?link={uuid} (GET, PATCH, PUT, POST заняты) - тело в ответ мы не получаем всё равно. Это ради того, чтобы оставить ручку в том же обработчике.

2) Либо PATCH /space/invitation/link (либо PUT, а вот POST /space/invitation/link уже занята) - только в этом случае код переносится в соседний обработчик.

**Comment by lirik90** [comment]
Второй вариант. Но давай сделаем чтобы метод был одинаковый с предыдущей ручкой POST. А текущий POST /space/invitation/link переделаем на PUT.
