### ISSUE TITLE
Исключить генерируемые на лету заголовки из генерации для angular

### ISSUE THREAD

**Issue by lirik90** [svetit-io/svetit#277]
Нашёл такое [ответ](https://stackoverflow.com/a/62496390/23748079) на so. В нём предлагается использовать какие то mustache template. Нужно попробовать разобраться с этим. По этому вопросу нашёл такие ссылки [один](https://www.baeldung.com/spring-boot-openapi-generator-custom-templates) и [два](https://openapi-generator.tech/docs/templating/). Чуть ниже в той ветке stackoverflow предлагали использовать настройку implicitHeadersRegex, но это только для spring, а для нашего генератора посмотрел такой настройки нет.

В той же ветке видел предложение сделать скрипт который перед генерацией будет удалять из исходного openapi ненужные нам заголовки. Если вариант с mustache template не сработает или слишком сложный, то тогда сделаем такой скрипт.

**Comment by prt0117** [comment]
Вот https://github.com/OpenAPITools/openapi-generator/blob/v7.3.0/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache один из шаблонов, который, судя по всему, нужно будет модифицировать, если идти по этому пути.

А вот - больше для интереса, но тоже можно подсмотреть что-то - ПР https://github.com/OpenAPITools/openapi-generator/pull/11819, который добавил в Спринговый генератор поддержку implicitHeadersRegex.

**Comment by prt0117** [comment]
Кстати, вот этот ответ https://stackoverflow.com/a/62496390, который ты выше упомянул, опирается на наличие в шаблонах @ApiImplicitParams - в ангуларовском генераторе я не вижу поддержки этой штуки. Так что если идти по пути шаблонов, то придётся её сначала реализовать в каком-то виде, судя по всему, а потом уже использовать, как в совете написано.

**Comment by prt0117** [comment]
По-моему, проще гораздо будет написать на баше скрипт, который седом снесёт все генерируемые на лету заголовки из path файлов. У нас всего 4 таких заголовка. Скрипт должен быть простым. Мы даже можем ещё сильнее упростить реализацию, если склеим все описания сначала в один файл (через redocly bundle), а потом пройдёмся по нему sed'ом.

**Comment by lirik90** [comment]
Отлично. Тогда давай в этой задаче сделаем скрипт.
Давай тогда сразу в этом скрипте попробуем убрать слово handler которое используется для генерации имён функций, чтобы функции получались с именем попроще.
