### ISSUE TITLE
Связи с группами в МС Проекты

### ISSUE THREAD

**Issue by lirik90** [svetit-io/svetit#278]
В МС Проекты сделать таблицы под связи группа-пользователь и группа-проект. Ручки для заполнения этих таблиц делать не надо.

**Comment by prt0117** [comment]
> Ручки для заполнения этих таблиц делать не надо.

Не нужно делать только Create и Update? А Read и Delete?

**Comment by lirik90** [comment]
Никакие ручки делать не нужно

**Comment by prt0117** [comment]
А что тогда написать? Табличные классы нужны для CRUD? Или только сами таблицы в миграциях описать и модели (структуры) создать?

**Comment by lirik90** [comment]
Только сами таблицы в миграциях описать. Без моделей
