### ISSUE TITLE
Таблица с ролями

### ISSUE THREAD

**Issue by lirik90** [svetit-io/svetit#279]
В МС Пространства сделать таблицу space.role (id SERIAL, space_id UUID, name VARCHAR (64), is_system BOOLEAN DEFAULT false)
Сделать уникальный ключ ON (name) WHERE is_system = TRUE
Сделать уникальный ключ ON (name, space_id) WHERE is_system = FALSE

При старте МС проверять есть ли в таблице роли admin, user, operator и если какой то нет, то вставлять.

**Comment by prt0117** [comment]
> Сделать уникальный ключ ON (name) WHERE is_system = TRUE

Это вот так примерно должно выглядеть?
```
CREATE UNIQUE INDEX system_role_constraint ON space.role (name) WHERE is_system=TRUE;
```
То есть это гарантирует, что в таблице будет только одна роль с уникальным именем, которая будет являться системной?

> Сделать уникальный ключ ON (name, space_id) WHERE is_system = FALSE

Это вот так примерно должно выглядеть?
```
CREATE UNIQUE INDEX not_system_role_constraint ON space.role (name, space_id) WHERE is_system=FALSE;
```
То есть такой уникальный ключ гарантирует, что в пространстве не будет ролей с одинаковыми именами, которые не будут при этом системными?

**Comment by lirik90** [comment]
Всё так

**Comment by prt0117** [comment]
А что нужно написать по этой задаче помимо описания таблиц в миграциях и моделей (структур)? Ручки для CRUD? Или CRUD только на уровне табличных классов?

**Comment by lirik90** [comment]
Да, давай сделаем ручки для CRUD, только поле is_system не может меняться или задаваться при вставке.

**Comment by prt0117** [comment]
> Да, давай сделаем ручки для CRUD, только поле is_system не может меняться или задаваться при вставке.

То есть всегда при INSERT is_system будет FALSE? 
И при UPDATE/PATCH его не сможем менять тоже?

> При старте МС проверять есть ли в таблице роли admin, user, operator и если какой то нет, то вставлять.

Это нужно будет делать для всех пространств в базе? 
А роль guest как-то будем учитывать? У нас же она сейчас в мс Пространства есть.
И что означает роль operator?

**Comment by prt0117** [comment]
И ещё вопрос - что делать со старой моделью под роли (enum): https://github.com/svetit-io/svetit/blob/develop/src/back/space/src/model/role.hpp ?

Сохранить ее пока, дав другое имя для модели новой роли, или сразу адаптировать под новую сущность роли?

**Comment by lirik90** [comment]
Извини, совсем забыл про то что там ещё и space_id. Что-то я поторопился и не продумал всё. ( Давай переделаем. Уберём поле is_system и сделаем space_id = NULL для такого кейса. И тогда при запросе списка возвращаем где либо space_id = NULL либо совпадает с переданным spaceId
При вставке и обновлении это поле всегда берём из хидера.
При старте заполняем системными и поле устанавливаем как NULL

**Comment by prt0117** [comment]
> и сделаем space_id = NULL для такого кейса

тогда мы не сможем внешний ключ для space_id использовать, это норм?

>  И тогда при запросе списка возвращаем где либо space_id = NULL либо совпадает с переданным spaceId

А для ручки списка ролей space_id будет задаваться query параметром, не из заголовка будет браться?

> При старте заполняем системными и поле устанавливаем как NULL

Не совсем понял.

> CREATE UNIQUE INDEX system_role_constraint ON space.role (name) WHERE is_system=TRUE;
> CREATE UNIQUE INDEX not_system_role_constraint ON space.role (name, space_id) WHERE is_system=FALSE;

Тогда если is_system не будет, то нужны ли эти индексы? Или их как-то переписать\адаптировать под отсутствие is_system? Например,

CREATE UNIQUE INDEX system_role_constraint ON space.role (name) WHERE space_id = NULL;
CREATE UNIQUE INDEX not_system_role_constraint ON space.role (name, space_id) WHERE space_id != NULL;

**Comment by lirik90** [comment]
> тогда мы не сможем внешний ключ для space_id использовать, это норм?

А почему не сможем? Разве там есть такое техническое ограничение?

> А для ручки списка ролей space_id будет задаваться query параметром, не из заголовка будет браться?

Всегда из заголовка



> Не совсем понял.

Вставляем admin, user, operator при старте



> Тогда если is_system не будет, то нужны ли эти индексы? Или их как-то переписать\адаптировать под отсутствие is_system? Например,
> 
> CREATE UNIQUE INDEX system_role_constraint ON space.role (name) WHERE space_id = NULL; 
> CREATE UNIQUE INDEX not_system_role_constraint ON space.role (name, space_id) WHERE space_id != NULL;

Да, именно так и адаптировать

**Comment by prt0117** [comment]
> > тогда мы не сможем внешний ключ для space_id использовать, это норм?
> 
> А почему не сможем? Разве там есть такое техническое ограничение?

Ок, почитал, вроде, так можно.

> 
> > А для ручки списка ролей space_id будет задаваться query параметром, не из заголовка будет браться?
> 
> Всегда из заголовка
> 

А если так, то как мы тогда будем выводить роль со space_id = NULL в списке, если space_id всегда будет прилетать в заголовке? Или для вывода системной роли со space_id =  NULL будет другая ручка?

>>>При старте заполняем системными и поле устанавливаем как NULL
>>
> > Не совсем понял.
> 
> Вставляем admin, user, operator при старте
> 

А admin, user, operator - это тоже системные роли?

> > Тогда если is_system не будет, то нужны ли эти индексы? Или их как-то переписать\адаптировать под отсутствие is_system? Например,
> > CREATE UNIQUE INDEX system_role_constraint ON space.role (name) WHERE space_id = NULL;
> > CREATE UNIQUE INDEX not_system_role_constraint ON space.role (name, space_id) WHERE space_id != NULL;
> 
> Да, именно так и адаптировать

Так у нас системная роль со space_id = NULL будет одна?

**Comment by lirik90** [comment]
Получение списка ролей where space_id IS NULL OR space_id = @spaceId

admin, user, operator - это три системные роли, других системных не будет

**Comment by prt0117** [comment]
> Получение списка ролей where space_id IS NULL OR space_id = @spaceid

Ок, спасибо, теперь понятно.

> admin, user, operator - это три системные роли, других системных не будет

В этом случае уникальный ключ 
CREATE UNIQUE INDEX idx_system_role ON space.role (name) WHERE space_id = NULL;
не позволит три системные роли со space_id = NULL поставить. Можно не использовать этот ключ тогда, наверное.

**Comment by lirik90** [comment]
> В этом случае уникальный ключ
> CREATE UNIQUE INDEX idx_system_role ON space.role (name) WHERE space_id = NULL;
> не позволит три системные роли со space_id = NULL поставить. Можно не использовать этот ключ тогда, наверное.

Нет, этот ключ сделает уникальным поле name для записей у которых space_id = NULL

**Comment by prt0117** [comment]
> > В этом случае уникальный ключ
> > CREATE UNIQUE INDEX idx_system_role ON space.role (name) WHERE space_id = NULL;
> > не позволит три системные роли со space_id = NULL поставить. Можно не использовать этот ключ тогда, наверное.
> 
> Нет, этот ключ сделает уникальным поле name для записей у которых space_id = NULL

ты прав, я сам ошибся во время тестовых SQL запросов.

**Comment by prt0117** [comment]
Вопросы по переписыванию на новые роли:

1) в таблицах смежных будем хранить, соответственно, int roleId с внешним ключом на таблицу space.role везде, где должна фигурировать роль?

Например, таблица space.user будет вот такой:
```
CREATE TABLE space.user (
	...
	roleId INT NOT NULL REFERENCES space.role (id),
	...
);
```
Верно?

2) сериализация\десериализация будет так же проходить, как и раньше? Из json получаем string (например, "admin"), в базе и объектах везде храним int (например, 3). Правильно?

3) получается в новом виде ролей может быть сколько угодно? При этом системных будет только 3. И, судя по всему, при валидации придётся теперь опираться не на захарждкоженные в enum значения, а на запрос в БД - если такая роль в таком пространстве есть в таблице с ролями, тогда ок. Если нету, то ошибка.

4) Что с ролью "Гость"? Она не нужна? Или её заменяет "Оператор"? Хотелось бы также понять, какой смысл закладывается сейчас в "Пользователя", какой в "Оператора". И какая из этих ролей сейчас выше по иерархии. Также относительно "Админа" - его смысл не поменялся? 

Ну и "Владелец" так же обособленно стоит (Администратор с отдельным признаком по сути)? Может, заодно ввести в обиход роль "Владелец"? А то у нас сейчас только проверками ограничивается ситуация, что не существует пользователя-владельца с ролью "Гость", например. Ну, это так, на всякий случай уточняю.

5) Вот в таких местах (https://github.com/svetit-io/svetit/blob/develop/src/back/space/src/api/introspect.cpp#L49), когда нам нужен именно "Админ" или "Пользователь", продолжаем вот так же строкой хардкодить роли? 
```
const std::string role = "admin";
const std::string token = _s.CreateToken(spaceIdStr, space.key, userId, role);
```

Можно так же, как и раньше использовать "admin", "user" и т.д.? Эти роли будут всегда во всех пространствах без каких-либо исключений?

6) А если нам нужно вот так (https://github.com/svetit-io/svetit/blob/develop/src/back/space/src/repo/repository.cpp#L181) сделать?
```
const pg::Query kSelectSpaceInvitation{
R"~(
	SELECT si.id, si.space_id, si.creator_id, si.user_id, si.role, si.created_at, COUNT(*) OVER()
	FROM space.invitation si
	WHERE si.user_id = $1 OR si.space_id IN (
		SELECT su.space_id FROM space.user su WHERE su.user_id = $1 AND su.role = 3
	) OFFSET $2 LIMIT $3
)~",
pg::Query::Name{"select_space.invitation"},
};
```
То как нам такую ситуацию лучше обыграть по-новому? Числовые айдишники ведь не зафиксированы у системных ролей? Или они всегда будут занимать первые 3 индекса - 1, 2, 3?

7) Судя по всему, добавление новой таблицы с ролями может привести к необходимости делать ещё один join или подзапрос в более-менее сложных SQL запросах. Либо даже дополнительный запрос делать отдельный. Например, вот тут (https://github.com/svetit-io/svetit/blob/develop/src/back/space/src/repo/repository.cpp#L263)
```
const pg::Query kInsertSpaceInvitation{
	R"~(
		INSERT INTO space.invitation (space_id, user_id, role, creator_id)
		(SELECT $1, $2, $3, $4
		WHERE EXISTS (
			SELECT 1 FROM space.space s
			LEFT JOIN space.user u ON s.id = u.space_id AND u.user_id=$4
			WHERE s.id=$1 AND (s.requests_allowed OR u.role=$5)
		)) RETURNING id
	)~",
	pg::Query::Name{"insert_space.invitation"},
};
```
добавится, судя по всему, проверка на существование роли с айдишником из вставляемого объекта. 

А вот тут (https://github.com/svetit-io/svetit/blob/develop/src/back/space/src/repo/table_space_user.cpp#L99), видимо, нужно будет задействовать как раз join.
```
bool SpaceUser::IsAdmin(const boost::uuids::uuid& spaceId, const std::string& userId) {
	const auto res = _db->Execute(ClusterHostType::kSlave, kGetRole, spaceId, userId);
	if (!res.IsEmpty()) {
		const auto role = res.AsSingleRow<Role::Type>();
		if (role == Role::Type::Admin)
			return true;
	}

	return false;
}
```
Это предварительно норм, что всё так?

8) Сейчас роль довольно часто фигурирует в сервисе (https://github.com/svetit-io/svetit/blob/develop/src/back/space/src/service/service.cpp). Соответственно, между методами сервиса и ручек мы будем передавать std::string roleName, верно?

То есть, допустим, метод

void Service::ChangeRoleInInvitation(int id, const Role::Type& role, const std::string& userId) {
	...
	_repo.SpaceInvitation().UpdateRole(id, role);
}

заменится у нас нас на

void Service::ChangeRoleInInvitation(int id, std::string roleName, const std::string& userId) {
	...
	_repo.SpaceInvitation().UpdateRole(id, roleName);
}

Пойдёт?

9) А вот в таких местах (https://github.com/svetit-io/svetit/blob/develop/src/back/space/src/service/service.cpp#L192), где у нас валидные роли были захардкожены, теперь какая у нас будет логика, например, конкретно в этом месте? 
```
static const std::set<Role::Type> valid_roles{
	Role::User, Role::Guest, Role::Admin
};
if (!valid_roles.contains(invitation.role))
	throw errors::BadRequest400("Wrong role");
```

На приглашение будут вешаться, наверное, не только системные роли, но и не системные? И все они будут валидны в этом случае, главное, чтобы они были заведены для соответствующего пространства в таблице с ролями?

10) Как у нас в новом формате будет обыгрываться вот такой кейс (https://github.com/svetit-io/svetit/blob/develop/src/back/space/src/service/service.cpp#L291)?
```
_repo.CreateInvitation(link.spaceId, creatorId, Role::Type::Unknown, creatorId);
```
Когда мы создаем приглашение без указания роли (приглашение по ссылке), будет ли у нас какая-то фиксированная роль Unknown для этого случая?

**Comment by prt0117** [comment]
Вопросы по ручкам для ролей в мс Пространство:

1) GET /space/role?id=<int>

В этой ручке мы должны проверить права, что пользователь из заголовка входит в пространстве из заголовка? Если нет, возвращаем 403. И если да, то смотрим, есть ли такая роль в этом пространстве по id, и возвращаем роль. Если нет такой роли, возвращаем 404.

2) POST /space/role 

Тело:
{
	"name": string
}

В этой ручке будем проверять права? Что пользователь из заголовка состоит в пространстве из заголовка, и что он админ в этом пространстве. Если нет, то 403. Если да, создаём новую роль в пространстве из заголовка.

3) PUT /space/role

Тело: 
{
	"id": int,
	"name": string
}

В этой ручке будем проверять права? Что пользователь из заголовка состоит в пространстве из заголовка, и что он админ в этом пространстве. Если нет, то 403. Если да, то даём изменить имя роли с id из тела, если эта роль существует в пространстве из заголовка.

4) DELETE /space/role?id=<int>

В этой ручке проверяем права? Что пользователь из заголовка админ в пространстве из заголовка. И если нет, то 403. А если да, то даём удалить роль с id из запроса.

5) GET /space/role/list?start=<int>&limit=<int>

В этой ручке проверяем права? Что пользователь из заголовка состоит в пространстве из заголовка. И если нет, то 403. А если да, то выводим списком все роли из пространства из заголовка. Кстати, системные роли тоже выводить в том же списке? Или не надо, так как они везде захардкожены?

6) Или все эти ручки сразу описываем под проксирование через мс Пространство? То есть
GET /s/<spaceKey:string>/space/role?id=<int>
POST /s/<spaceKey:string>/space/role
PUT /s/<spaceKey:string>/space/role
DELETE /s/<spaceKey:string>/space/role?id=<int>

**Comment by lirik90** [comment]
> Вопросы по ручкам для ролей в мс Пространство:
> 
> 1. GET /space/role?id=
> 
> В этой ручке мы должны проверить права, что пользователь из заголовка входит в пространстве из заголовка? Если нет, возвращаем 403. И если да, то смотрим, есть ли такая роль в этом пространстве по id, и возвращаем роль. Если нет такой роли, возвращаем 404.
> 

Нет, всё что в заголовках уже проверено. В запросе проверяем что запрошенная роль либо id = $1 AND (space_id IS NULL OR space_id = $2) где $2 это значение из хидера.

> 2. POST /space/role
> 
> Тело: { "name": string }
> 
> В этой ручке будем проверять права? Что пользователь из заголовка состоит в пространстве из заголовка, и что он админ в этом пространстве. Если нет, то 403. Если да, создаём новую роль в пространстве из заголовка.
> 

В этой ручке проверяем установлен ли хидер is_admin в 1.  только админ может создать роль

> 3. PUT /space/role
> 
> Тело: { "id": int, "name": string }
> 
> В этой ручке будем проверять права? Что пользователь из заголовка состоит в пространстве из заголовка, и что он админ в этом пространстве. Если нет, то 403. Если да, то даём изменить имя роли с id из тела, если эта роль существует в пространстве из заголовка.
> 

Также как в первом + во втором вопросе. Т.е. сначала проверяем хидер is_admin потом в запросе добавляем хвост как в первом вопросе

> 4. DELETE /space/role?id=
> 
> В этой ручке проверяем права? Что пользователь из заголовка админ в пространстве из заголовка. И если нет, то 403. А если да, то даём удалить роль с id из запроса.
> 

Как в предыдущем вопросе.

> 5. GET /space/role/list?start=&limit=
> 
> В этой ручке проверяем права? Что пользователь из заголовка состоит в пространстве из заголовка. И если нет, то 403. А если да, то выводим списком все роли из пространства из заголовка. Кстати, системные роли тоже выводить в том же списке? Или не надо, так как они везде захардкожены?
> 

Нет, ничего не проверяем.


> 6. Или все эти ручки сразу описываем под проксирование через мс Пространство? То есть
>    GET /s/spaceKey:string/space/role?id=
>    POST /s/spaceKey:string/space/role
>    PUT /s/spaceKey:string/space/role
>    DELETE /s/spaceKey:string/space/role?id=

Верно

**Comment by prt0117** [comment]
Вопрос появился - а мы даём возможность в рамках текущей задачи удалять (delete) или менять (update) системные роли?

**Comment by lirik90** [comment]
Нет, не даём возможность
